// ─── DEMO SEED DATA ─────────────────────────────────────────────────────────

export const DEMO_TRIPS = [
  {
    id: "t1",
    traveler: { id: "u1", name: "Arif Rahman", avatar: "", rating: 4.9, reviews: 47, verified: true, kycLevel: "full", country: "BD" },
    from: { city: "Dhaka", country: "Bangladesh", airport: "DAC", code: "BD" },
    to: { city: "London", country: "United Kingdom", airport: "LHR", code: "GB" },
    departureDate: "2026-07-15",
    arrivalDate: "2026-07-15",
    airline: "Biman Bangladesh Airlines",
    freeKg: 15,
    allowedCategories: ["Electronics","Clothing","Documents","Food (dry, sealed)"],
    compensation: "Negotiable",
    compensationMin: 20,
    compensationMax: 80,
    ticketSponsorship: false,
    pickupAvailable: true,
    dropAvailable: false,
    status: "Active",
    createdAt: "2026-06-20",
  },
  {
    id: "t2",
    traveler: { id: "u2", name: "Fatima Al-Mansouri", avatar: "", rating: 4.8, reviews: 32, verified: true, kycLevel: "full", country: "AE" },
    from: { city: "Dubai", country: "UAE", airport: "DXB", code: "AE" },
    to: { city: "Toronto", country: "Canada", airport: "YYZ", code: "CA" },
    departureDate: "2026-07-22",
    arrivalDate: "2026-07-22",
    airline: "Emirates",
    freeKg: 20,
    allowedCategories: ["Clothing","Jewelry","Cosmetics","Documents"],
    compensation: "Fixed",
    compensationMin: 50,
    compensationMax: 50,
    ticketSponsorship: true,
    pickupAvailable: true,
    dropAvailable: true,
    status: "Active",
    createdAt: "2026-06-21",
  },
  {
    id: "t3",
    traveler: { id: "u3", name: "Raj Sharma", avatar: "", rating: 4.7, reviews: 19, verified: true, kycLevel: "basic", country: "IN" },
    from: { city: "Delhi", country: "India", airport: "DEL", code: "IN" },
    to: { city: "Sydney", country: "Australia", airport: "SYD", code: "AU" },
    departureDate: "2026-08-03",
    arrivalDate: "2026-08-04",
    airline: "Air India",
    freeKg: 10,
    allowedCategories: ["Clothing","Documents","Herbal Products"],
    compensation: "Negotiable",
    compensationMin: 30,
    compensationMax: 60,
    ticketSponsorship: false,
    pickupAvailable: false,
    dropAvailable: true,
    status: "Active",
    createdAt: "2026-06-22",
  },
  {
    id: "t4",
    traveler: { id: "u4", name: "Elif Yıldız", avatar: "", rating: 5.0, reviews: 63, verified: true, kycLevel: "full", country: "TR" },
    from: { city: "Istanbul", country: "Turkey", airport: "IST", code: "TR" },
    to: { city: "New York", country: "USA", airport: "JFK", code: "US" },
    departureDate: "2026-07-30",
    arrivalDate: "2026-07-30",
    airline: "Turkish Airlines",
    freeKg: 25,
    allowedCategories: ["Clothing","Electronics","Ceramics","Textiles","Cosmetics"],
    compensation: "Negotiable",
    compensationMin: 40,
    compensationMax: 120,
    ticketSponsorship: false,
    pickupAvailable: true,
    dropAvailable: true,
    status: "Active",
    createdAt: "2026-06-18",
  },
  {
    id: "t5",
    traveler: { id: "u5", name: "Ahmad Zulkifli", avatar: "", rating: 4.6, reviews: 12, verified: true, kycLevel: "basic", country: "MY" },
    from: { city: "Kuala Lumpur", country: "Malaysia", airport: "KUL", code: "MY" },
    to: { city: "Doha", country: "Qatar", airport: "DOH", code: "QA" },
    departureDate: "2026-07-18",
    arrivalDate: "2026-07-18",
    airline: "Qatar Airways",
    freeKg: 12,
    allowedCategories: ["Clothing","Electronics","Documents"],
    compensation: "Negotiable",
    compensationMin: 25,
    compensationMax: 70,
    ticketSponsorship: true,
    pickupAvailable: false,
    dropAvailable: false,
    status: "Active",
    createdAt: "2026-06-23",
  },
  {
    id: "t6",
    traveler: { id: "u6", name: "Sophie Martin", avatar: "", rating: 4.9, reviews: 28, verified: true, kycLevel: "full", country: "FR" },
    from: { city: "Paris", country: "France", airport: "CDG", code: "FR" },
    to: { city: "Dhaka", country: "Bangladesh", airport: "DAC", code: "BD" },
    departureDate: "2026-08-10",
    arrivalDate: "2026-08-11",
    airline: "Qatar Airways",
    freeKg: 18,
    allowedCategories: ["Clothing","Cosmetics","Documents","Books"],
    compensation: "Fixed",
    compensationMin: 60,
    compensationMax: 60,
    ticketSponsorship: false,
    pickupAvailable: true,
    dropAvailable: false,
    status: "Active",
    createdAt: "2026-06-24",
  },
];

export const DEMO_SHIPMENTS = [
  {
    id: "s1",
    sender: { id: "u7", name: "Tanvir Hossain", avatar: "", rating: 4.8, reviews: 15, verified: true, country: "BD" },
    title: "Samsung Galaxy S24 (1 unit, personal use)",
    category: "Electronics",
    description: "Brand new Samsung Galaxy S24, purchased from official store. Box sealed, invoice included. For personal use.",
    weight: 0.5,
    dimensions: "16×8×1 cm",
    declaredValue: 850,
    currency: "USD",
    photos: 4,
    invoiceUploaded: true,
    quantity: 1,
    from: { city: "London", country: "UK", code: "GB" },
    to: { city: "Dhaka", country: "Bangladesh", code: "BD" },
    dateFlexibility: "±3 days",
    urgency: "Medium",
    offerPrice: 45,
    customsDutyResponsibility: "Sender",
    status: "Active",
    highRisk: true,
    createdAt: "2026-06-22",
  },
  {
    id: "s2",
    sender: { id: "u8", name: "Priya Nair", avatar: "", rating: 4.7, reviews: 9, verified: true, country: "IN" },
    title: "Herbal Ayurvedic Medicines (sealed, labeled)",
    category: "Medicine / Health",
    description: "Legally purchased Ayurvedic supplements, sealed in original packaging with pharmacy invoice.",
    weight: 2.0,
    dimensions: "30×20×15 cm",
    declaredValue: 120,
    currency: "USD",
    photos: 6,
    invoiceUploaded: true,
    quantity: 5,
    from: { city: "Dubai", country: "UAE", code: "AE" },
    to: { city: "Delhi", country: "India", code: "IN" },
    dateFlexibility: "Exact date",
    urgency: "High",
    offerPrice: 30,
    customsDutyResponsibility: "Recipient",
    status: "Active",
    highRisk: false,
    createdAt: "2026-06-20",
  },
  {
    id: "s3",
    sender: { id: "u9", name: "Carlos Mendez", avatar: "", rating: 4.9, reviews: 22, verified: true, country: "MX" },
    title: "Handmade Leather Goods (3 wallets)",
    category: "Clothing & Fashion",
    description: "Handcrafted leather wallets, gift for family. Packed in protective wrap. Receipt included.",
    weight: 0.8,
    dimensions: "25×15×5 cm",
    declaredValue: 180,
    currency: "USD",
    photos: 3,
    invoiceUploaded: true,
    quantity: 3,
    from: { city: "Toronto", country: "Canada", code: "CA" },
    to: { city: "Mexico City", country: "Mexico", code: "MX" },
    dateFlexibility: "±5 days",
    urgency: "Low",
    offerPrice: 25,
    customsDutyResponsibility: "Sender",
    status: "Active",
    highRisk: false,
    createdAt: "2026-06-21",
  },
];

export const DEMO_SPONSORSHIPS = [
  {
    id: "sp1",
    type: "request", // traveler seeking sponsor
    traveler: { id: "u10", name: "Md. Karim", avatar: "", rating: 4.5, reviews: 8, verified: true, country: "BD" },
    from: { city: "Dhaka", country: "Bangladesh", airport: "DAC", code: "BD" },
    to: { city: "London", country: "UK", airport: "LHR", code: "GB" },
    dateRange: "July 20 – August 5, 2026",
    canCarryKg: 20,
    acceptedCategories: ["Clothing","Electronics","Documents","Food (dry)"],
    ticketBudgetNeeded: 850,
    currency: "USD",
    partialOk: true,
    description: "Experienced carrier, 8 successful deliveries. Can carry up to 20kg of legal declared items in exchange for full or partial ticket sponsorship.",
    status: "Active",
    createdAt: "2026-06-22",
  },
  {
    id: "sp2",
    type: "offer", // sponsor seeking traveler
    sponsor: { id: "u11", name: "NovaTech Imports", avatar: "", rating: 4.8, reviews: 34, verified: true, country: "AE" },
    from: { city: "Dubai", country: "UAE", airport: "DXB", code: "AE" },
    to: { city: "Toronto", country: "Canada", airport: "YYZ", code: "CA" },
    dateRange: "July 25 – August 10, 2026",
    cargoKg: 15,
    cargoCategories: ["Electronics"],
    cargoDescription: "Consumer electronics (phones and accessories), fully declared with invoices and IMEI numbers.",
    ticketBudget: 1200,
    currency: "USD",
    partialOk: false,
    description: "Looking for a verified traveler to carry legally declared electronics. Full economy ticket covered. Items open for inspection.",
    status: "Active",
    createdAt: "2026-06-21",
  },
  {
    id: "sp3",
    type: "request",
    traveler: { id: "u12", name: "Aisha Kamara", avatar: "", rating: 4.9, reviews: 21, verified: true, country: "SL" },
    from: { city: "Freetown", country: "Sierra Leone", airport: "FNA", code: "SL" },
    to: { city: "London", country: "UK", airport: "LHR", code: "GB" },
    dateRange: "August 1–15, 2026",
    canCarryKg: 15,
    acceptedCategories: ["Clothing","Documents","Jewelry (declared)"],
    ticketBudgetNeeded: 780,
    currency: "USD",
    partialOk: true,
    description: "Professional courier with strong references. Open to full or partial sponsorship for legal cargo.",
    status: "Active",
    createdAt: "2026-06-23",
  },
];

export const COUNTRY_RULES = [
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    customsThreshold: 1000,
    currency: "AUD",
    strictFood: true,
    strictMedicine: true,
    electronics: "Duty-free up to AUD 1,000 personal imports. ACMA compliance for wireless devices.",
    food: "⚠️ STRICT: Most fresh food, seeds, plant material prohibited. Declare ALL food. Biosecurity fines up to AUD 525,000.",
    medicine: "Personal use quantity only. Prescription must accompany controlled substances.",
    phones: "Up to 2 phones personal use. Commercial quantities trigger duty and GST.",
    batteries: "Lithium batteries must meet IATA standards. Loose batteries in carry-on only.",
    notes: "Australia has among the world's strictest biosecurity laws. When in doubt, declare.",
    restricted: ["Fresh produce","Seeds","Live animals","Soil","Untreated wood"],
  },
  {
    code: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
    customsThreshold: 300,
    currency: "BDT",
    strictFood: false,
    strictMedicine: false,
    electronics: "Duty-free for 1 laptop + 1 phone for personal use. Additional phones attract 25–37.5% duty.",
    food: "Commercially packed food generally allowed. Meat products require halal certification.",
    medicine: "Personal use quantity allowed. Original packaging preferred.",
    phones: "1 personal-use phone duty-free. 2nd phone onwards: duty + VAT applies (~25–37.5%). IMEI registration required.",
    batteries: "Standard IATA rules apply.",
    notes: "Gift allowance: up to BDT 10,000 duty-free. Declare all electronics at Dhaka customs.",
    restricted: ["Narcotics","Pornographic material","Israeli goods (formally)","Counterfeit goods"],
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    customsThreshold: 800,
    currency: "CAD",
    strictFood: false,
    strictMedicine: false,
    electronics: "Electronics generally allowed for personal use. Duty may apply on commercial quantities.",
    food: "Most commercially packaged food allowed. Fresh fruits/vegetables from some countries restricted.",
    medicine: "90-day supply for personal use. Controlled substances need prescription.",
    phones: "Personal use phones generally duty-free. Commercial import needs broker.",
    batteries: "IATA lithium battery rules apply. Airlines may restrict quantity.",
    notes: "CBSA requires declaration of all goods over CAD 800. Gift exemption CAD 60.",
    restricted: ["Firearms (without permit)","Endangered species products","Hate propaganda"],
  },
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    customsThreshold: 390,
    currency: "GBP",
    strictFood: false,
    strictMedicine: false,
    electronics: "Duty-free for personal use up to £390. VAT + customs above threshold.",
    food: "Post-Brexit: meat and dairy from non-GB origins restricted. Commercial quantities need health certificate.",
    medicine: "3-month personal supply. Controlled drugs need Home Office licence.",
    phones: "1-2 phones personal use typically cleared. HMRC monitors commercial volumes.",
    batteries: "Lithium batteries: IATA rules. Power banks carry-on only.",
    notes: "Post-Brexit rules apply. HMRC Random Inspection Channel (Red/Green/Nothing to Declare).",
    restricted: ["Offensive weapons","Endangered species","Counterfeit goods","Ivory"],
  },
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    customsThreshold: 3000,
    currency: "AED",
    strictFood: false,
    strictMedicine: true,
    electronics: "Generally liberal. Commercial quantities need trade license.",
    food: "Pork products restricted. Halal certification needed for meat.",
    medicine: "⚠️ Strict: Many prescription drugs illegal. Check MOH list before carrying ANY medication.",
    phones: "Personal use liberal. Bulk quantities need customs declaration.",
    batteries: "IATA standards apply. DGCA regulations for aviation.",
    notes: "Some medications legal elsewhere are ILLEGAL in UAE. Always verify at uae.gov.ae. Penalties severe.",
    restricted: ["Pork (publicly displayed)","Alcohol (non-personal)","Certain medications","VoIP devices (legacy)","Gambling items"],
  },
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    customsThreshold: 800,
    currency: "USD",
    strictFood: false,
    strictMedicine: false,
    electronics: "Generally liberal. FCC certification required for wireless devices.",
    food: "Fresh produce restrictions. USDA regulates meat, dairy, fruits, vegetables.",
    medicine: "FDA personal use policy: 90-day supply. Must be for personal use.",
    phones: "Unlocked phones fine. Commercial imports may need FCC ID.",
    batteries: "FAA/DOT rules: lithium ion max 100Wh per battery in carry-on.",
    notes: "CBP duty-free exemption: $800 per person. Gifts up to $100. FinCEN: declare cash/monetary instruments over $10,000.",
    restricted: ["Cuban cigars (over limit)","Products of forced labor","Endangered species","Certain medications without prescription"],
  },
  {
    code: "IN",
    name: "India",
    flag: "🇮🇳",
    customsThreshold: 50000,
    currency: "INR",
    strictFood: false,
    strictMedicine: false,
    electronics: "Duty-free one laptop. Additional electronics: 15–28% BCD + GST.",
    food: "Commercially sealed generally okay. Meat, seafood restrictions apply.",
    medicine: "Personal use quantity. Ayurvedic/herbal allowed. Controlled substances need permit.",
    phones: "1 phone duty-free with up to INR 50,000 total goods. Additional: 15–20% duty.",
    batteries: "DGCA lithium rules. Airlines restrict loose lithium cells.",
    notes: "Indian Customs: Baggage Rules 2016. Residents returning: INR 50,000 duty-free. Tourists: INR 15,000.",
    restricted: ["Satellite phones (without permission)","GPS devices (restricted zones)","Drones (without DGCA approval)","Counterfeit goods"],
  },
];

export const PROHIBITED_ITEMS = [
  { category: "Narcotics & Drugs", icon: "🚫", description: "All illegal drugs, narcotics, and controlled substances. Zero tolerance.", severity: "absolute" },
  { category: "Weapons & Explosives", icon: "💣", description: "Firearms, ammunition, explosives, knives (carry-on). Check airline/country rules.", severity: "absolute" },
  { category: "Hazardous Materials", icon: "☢️", description: "Radioactive material, corrosives, flammable liquids beyond limits, toxic substances.", severity: "absolute" },
  { category: "Counterfeit Goods", icon: "🏷️", description: "Fake branded items, pirated software, counterfeit currency. Illegal in all jurisdictions.", severity: "absolute" },
  { category: "Large Cash (Undeclared)", icon: "💵", description: "Cash over $10,000 USD (or equivalent) must be declared. Undeclared = seizure + penalty.", severity: "absolute" },
  { category: "Gold Bullion (Undeclared)", icon: "🥇", description: "Commercial quantities of gold/bullion without declaration and permits.", severity: "absolute" },
  { category: "Unknown Sealed Packages", icon: "📦", description: "CarryBridge strictly prohibits carrying any sealed package whose contents are unknown to the carrier.", severity: "absolute" },
  { category: "Live Animals", icon: "🐾", description: "Live animals require specific documentation, health certificates, and permits.", severity: "absolute" },
  { category: "Illegal Medicines", icon: "💊", description: "Prescription drugs without valid prescription, medicines banned in destination country.", severity: "absolute" },
  { category: "Pornographic Material", icon: "🔞", description: "Illegal in many countries including UAE, Qatar, Bangladesh, Saudi Arabia.", severity: "absolute" },
  { category: "Endangered Species Products", icon: "🦏", description: "Ivory, certain animal products, protected species items. CITES violation.", severity: "absolute" },
  { category: "Lithium Batteries (Bulk)", icon: "🔋", description: "Bulk/commercial quantities. Personal use okay with IATA limits. Declare all.", severity: "conditional" },
  { category: "Food (Fresh/Unpackaged)", icon: "🍎", description: "Fresh produce restricted in many countries (Australia, USA, NZ). Always declare.", severity: "conditional" },
  { category: "Commercial Quantity Electronics", icon: "📱", description: "Multiple phones/devices may trigger commercial import duties. Limit to personal quantities.", severity: "conditional" },
];

export const BOOKING_STATUSES = [
  "Draft","Active","Matched","Requested","Accepted",
  "Escrow Pending","Pickup Scheduled","Picked Up",
  "In Transit","Arrived","Delivered","Completed",
  "Disputed","Cancelled"
] as const;

export const ITEM_CATEGORIES = [
  "Electronics","Clothing & Fashion","Documents","Books & Media",
  "Food (dry, sealed, packaged)","Cosmetics & Beauty","Medicine / Health",
  "Jewelry (declared)","Toys & Baby Products","Herbal / Ayurvedic",
  "Ceramics & Handicrafts","Textiles & Fabrics","Sports Equipment",
  "Kitchenware","Personal Care","Other (declared)"
];

export const DEMO_MESSAGES = [
  {
    id: "m1",
    bookingId: "b1",
    sender: "Arif Rahman",
    text: "Hi, I can carry your item on my July 15 flight. Can you share more photos?",
    time: "2 hours ago",
    isMe: false,
  },
  {
    id: "m2",
    bookingId: "b1",
    sender: "You",
    text: "Sure! I'll upload 4 angle photos right away. The item is fully packed in original box with invoice.",
    time: "1 hour ago",
    isMe: true,
  },
  {
    id: "m3",
    bookingId: "b1",
    sender: "Arif Rahman",
    text: "Perfect. I've reviewed the photos. Looks good. Can we agree on £40 for carrying fee?",
    time: "45 min ago",
    isMe: false,
  },
];

export const DEMO_USER = {
  id: "me",
  name: "Jordan Lee",
  email: "jordan@example.com",
  role: "sender",
  verified: true,
  kycLevel: "full",
  trustScore: 94,
  rating: 4.8,
  reviews: 12,
  completionRate: 100,
  cancellationRate: 0,
  country: "GB",
  memberSince: "2025-03-01",
  activeBookings: 2,
  pendingActions: 3,
};
